name: Initialize Publish-Branche

jobs:
  create-publish:
    runs-on:
      name: Deploy to Publish-Branche
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: publish
        folder: docs